### ISSUE TITLE
(suggestion) 16x9 Scene Preview Images, 9:16 or other portarait AR for Performers

### ISSUE THREAD

**Issue by GernBlanston12** [boi123212321/porn-manager#109]
Hi, just wanted to suggest making Scene preview images 16x9, as this AR is 99% of all porn manufactured.  I'd also like to suggest some sort of portrait AR for Performers/Stars, rather than the nearly square, stout-looking rectangle you're using now. If you're like me, you want centerfold-style preview images for your porn actors, not a square portrait, but it's a matter of taste so I won't hold it against you if you don't like/implement it. Most of what I've seen of existing porn organizing is set up like this, though.

**Comment by boi123212321** [comment]
I've thought about this, and there's a reason I went with square images for now (they're actually 1:1) - they're really neutral, especially when using the cropping function. However, it would probably be best to add the ability to change the cropping AR and the representation in the lists (1:1, 16:9, 9:16? I guess); shouldn't be too hard to add, either.

**Comment by boi123212321** [comment]
OK, scrap what I said, it was actually pretty trivial to implement;
As of 0.4.1 (https://github.com/boi123212321/porn-manager/releases/tag/0.4.1), it is possible to change the aspect ratio for scenes/actors independently, may add more ratios if needed.

**Comment by GernBlanston12** [comment]
Thanks for the speedy delivery!
