### ISSUE TITLE
Importing a very large image library fails

### ISSUE THREAD

**Issue by boi123212321** [boi123212321/porn-manager#128]
https://github.com/boi123212321/porn-manager/issues/120

**Comment by boi123212321** [comment]
I've rewritten the image import on 0.4.9

https://github.com/boi123212321/porn-manager/releases/tag/0.4.9

**Comment by cloudstrife11** [comment]
Lol you are working very hard over there going to test soon:)

**Comment by cloudstrife11** [comment]
Nice now it working, now I also can see whats import in the program. The only thing is it imports realy slow Its taking 1 sec for 1 image so it takes around 28 hours to import all of my images :(

**Comment by boi123212321** [comment]
@cloudstrife11 Currently it calculates the dimensions and a fingerprint of every image which slows it down.
I could add an option to disable that, however that would mean losing all metadata (width, height, filesize, hash). Tags and actors would still be extracted from the filename.

**Comment by cloudstrife11** [comment]
Can you add that option only for testing. So I can see if I like that better. Only if thats not taking much time to add.

**Comment by boi123212321** [comment]
@cloudstrife11 Can you try 0.4.11?
Disabling image reading (in config.json) boosted my import speed from ~1 second per image to ~1 second per 250 images

https://github.com/boi123212321/porn-manager/releases/tag/0.4.11

**Comment by cloudstrife11** [comment]
Yes why much faster it imported 3437 images in +19seconds

**Comment by boi123212321** [comment]
I'll close this issue for now, feel free to open a new one
