### ISSUE TITLE
Inheritable Labels

### ISSUE THREAD

**Issue by porncloud** [boi123212321/porn-manager#133]
I'm not sure if this is something that should work, and I'm not understanding, or if its a suggestion!

I added some scenes for an actor, the actor already has a label assigned.  I added the actor to the scenes but the label was not applied to the scenes?  

The same would be great for studios, adding a tag to a studio would apply to any scene for that studio?

**Comment by boi123212321** [comment]
As long as APPLY_ACTOR_LABELS is enabled in the config.json, all actor labels are transferred to the scene *on import* .
> Whether actor labels should be applied to scenes and images the actor is starring in
Example: Kali Roses has labels "blonde" & "tattoos". Importing a new video featuring Kali Roses (will be matched if "Kali Roses" is in the video title or path), the newly created scene will automatically inherit "blonde" & "tattoos" + other labels that have been extracted from the title or path.

Currently, when you add an actor to a scene *after* it has already been created it will not get the actor's labels. But you have a point, maybe they should still be applied then as well.

Labels on studios will happen in the future. Currently it just shows labels inferred from its scenes.

**Comment by boi123212321** [comment]
> I added some scenes for an actor, the actor already has a label assigned. I added the actor to the scenes but the label was not applied to the scenes?
I have added this now in 0.4.12

> The same would be great for studios, adding a tag to a studio would apply to any scene for that studio?
& this feature will definitely come in the future

**Comment by porncloud** [comment]
Great stuff, when you said in the future I assumed weeks/months ;)

**Comment by cloudstrife11** [comment]
Not working with version  0.5.0!
