### ISSUE TITLE
Scale UI

### ISSUE THREAD

**Issue by porncloud** [boi123212321/porn-manager#136]
When you open the webpage on a higher resolution it doesn't scale, for example on a 4k screen the scenes page has the six scenes per row, but at either side there is a fairly large gap.

On an unrelated note, have you considered setting up a Discord, I have a few other suggestions but I don't really like making issues without discussing them first as some might just be personal.

**Comment by boi123212321** [comment]
I don't have a 4k screen; can you give me a screenshot of how it looks in Discord?
Setup https://discord.gg/t499hxK
