### ISSUE TITLE
On label creation: check & attach to existing videos

### ISSUE THREAD

**Issue by cloudstrife11** [boi123212321/porn-manager#140]
You  had this closed yesterday. But this still not working. When I add labels after my videos import the labels not added anymore to the video files. I have the version 0.5.0. Maybe i did something wrong. Or I dumb not understand it that you still want to make this in the future.

**Comment by boi123212321** [comment]
What are you doing exactly? Because it's working for me.

**Comment by cloudstrife11** [comment]
First I downloaded 0.5.0 I extracted it. I run it. did the messages that the manager give. changed the scanning on startup to true. then restart it. now it imported all of my videofiles. Generated the thumbnails. Then I added the labels. But the labels will not been assigned to the videofiles.

**Comment by boi123212321** [comment]
ohh this is different from #133 which was about actor and studio labels being attached to scenes.
What you want is that after every label you add the program goes through every video and checks if the video is eligible for that label, and then adds that. I think i'm getting that right.

The workaround right now is to keep scanning on startup disabled, add your labels, then enable scan & restart the server.

**Comment by cloudstrife11** [comment]
Oke I think you understand now:)

**Comment by boi123212321** [comment]
@cloudstrife11 Yes, generally, create actors, labels & studios first, then enable import and it should extract all of it from the file paths.

**Comment by cloudstrife11** [comment]
Then I hope you will make a actors bulk import from txt or anything else. Because I am not going to do it now because it wil takes weeks to import 1b1 my actors;(

**Comment by boi123212321** [comment]
You can join the Discord
https://discord.gg/t499hxK for real time updates
and chatting for suggestions without creating an issue every time

**Comment by boi123212321** [comment]
You can join the Discord
https://discord.gg/t499hxK for real time updates
and chatting for suggestions without creating an issue every time @cloudstrife11
