### ISSUE TITLE
how to build the bin of ffmpeg,i get follow error

### ISSUE THREAD

**Issue by gsons** [boi123212321/porn-manager#15]
`Uncaught Error: spawn \win-unpacked\bin\ffmpeg.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264)
    at onErrorNT (internal/child_process.js:456)
    at processTicksAndRejections (internal/process/task_queues.js:84)`

**Comment by boi123212321** [comment]
Hi there,

first off, this repo is extremely work in progress and I do not recommend anybody using it unless you're into actively developing it or are patient enough to wait until it's more finished.
Now we've got that out of the way...

On Windows, when you're in app folder, run:
```
npm run electron:build
xcopy "bin/win" "build\win-unpacked\bin\win" /E
Press 'D'
```
This should do the trick.

I'll add an option to change the paths to the .exe files at some point.
Track here https://github.com/boi123212321/porn-manager/issues/16

**Comment by boi123212321** [comment]
FFMpeg/probe paths can now be changed in settings as of #16
