### ISSUE TITLE
Bulk import studio logos

### ISSUE THREAD

**Issue by echo6ix** [boi123212321/porn-manager#162]
Add a method for bulk importing studio logos located in a folder. In the bulk import area, add a toggle option that asks the user if they want to overwrite any already existing studio logos.

**Comment by Red5ive-UK** [comment]
Would be great to have the ability to download these from a repository such as:
https://gitea.unknown.name/Trizkat/site-logos

Either as a program feature or by plugin.

**Comment by boi123212321** [comment]
i guess this can be done using bulk imports
