### ISSUE TITLE
Actress Biography + Search Integration

### ISSUE THREAD

**Issue by johnnyporn88** [boi123212321/porn-manager#172]
A way to scrape actress profiles from sites like FreeOnes, Data18, or IAFD.

Then, allow search queries and filtering of results based on the biography. e.g., search by hair color, nationality, height, age, breast cup sizes, etc.

**Comment by tltgt** [comment]
I'd second this!

**Comment by tritnaha** [comment]
Yeah, being able to scrape actor-info via FreeOnes/Data18/IAFD/metadataapi would be lovely. Even scenes too maybe?
