### ISSUE TITLE
[Feature] Add exclude patterns

### ISSUE THREAD

**Issue by tltgt** [boi123212321/porn-manager#188]
I'd love to see the ability to exclude certain file patterns, e.g. files starting with a dot. Thanks for the great work!

**Comment by boi123212321** [comment]
Perhaps adding glob support (https://www.npmjs.com/package/glob) for the import folders would work nicely

**Comment by tltgt** [comment]
Using https://www.npmjs.com/package/glob you could specify the (list of) path and list of extensions
- Import from /myvideos/* (recursively)
- Import *.mp4, mpeg, .mov
So far the above can be specified as /myvideos/**/*.{mp4,mpeg,mov} if I'm not mistaken

However, how could you also specify exclude patterns in that?

**Comment by boi123212321** [comment]
Excludes would have be done separately, as you mentioned, probably using Regex.

You examples as globs would be:

- /myvideos/**/*
- /myvideos/**/*.{mp4,mpeg,mov}

**Comment by tritnaha** [comment]
Is it currently possible to exclude anything containing the name "sample"?
