### ISSUE TITLE
[Bug] File names with dots truncated

### ISSUE THREAD

**Issue by tltgt** [boi123212321/porn-manager#190]
When a file has dots `like.this.file.name.is.mpg` it ended up being added as `like`, i.e. only the first part before the dot.

It should pick up as `like.this.file.name.is`

Also perhaps there should be a plugin/addon system that cleans up and processes the file name so the title of the video becomes `Like This File Name Is` or something to that effect.

**Comment by tltgt** [comment]
in `src/queue/index.ts`
change
```
    const fileNameWithoutExtension = item.filename.split(".")[0]
```
to:
```
    const fileNameWithoutExtension = item.filename.replace(/\.[^/.]+$/, "");
```

**Comment by boi123212321** [comment]
Works on dev, will be in next version
Thanks!
