### ISSUE TITLE
[Feature] Pause video in the background

### ISSUE THREAD

**Issue by tltgt** [boi123212321/porn-manager#194]
When the browser window lost focus, the video playback should be paused. This can be made as an option if possible.

**Comment by boi123212321** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
``` javascript
document.addEventListener( 'visibilitychange' , () => {
    if (document.hidden)
       // Hide video
}, false );
```

Has good browser support as well
https://caniuse.com/#feat=pagevisibility

**Comment by tltgt** [comment]
Make it auto resume when the focus is back please
