### ISSUE TITLE
[Feature] Speed up UI

### ISSUE THREAD

**Issue by tltgt** [boi123212321/porn-manager#206]
Is it possible to cache the results so that when we switched between Home / Scenes / Actors etc, it doesn't have to reload? The reload process is very slow.

Of course it would be great to also speed up the reload process. As it is, browsing is a painfully slow process.

**Comment by tltgt** [comment]
Using src/graphql/resolvers/query.ts/getScenes() for example, the bottleneck is in this code:
```
    let searchDocs = await Promise.all(
      allScenes.map(async scene => ({
        _id: scene._id,
        name: scene.name,
        releaseDate: scene.releaseDate,
        favorite: scene.favorite,
        bookmark: scene.bookmark,
        rating: scene.rating,
        labels: await Scene.getLabels(scene), //***
        actors: await Scene.getActors(scene), //***
        addedOn: scene.addedOn,
        watches: scene.watches,
        duration: scene.meta.duration || 0,
        studio: scene.studio,
        movies: await Movie.getByScene(scene._id), //*** 
        studioObj: scene.studio ? await Studio.getById(scene.studio) : null
      }))
    );
```

I've marked the parts that caused the slow down. What can we do to optimise it?

Also perhaps instead of fetching everything and then only returning the needed entries, why not filter the query in the first place, i.e. not use Scene.getAll(). That will also reduce the number of iterations needed by allScenes.map() above.

**Comment by boi123212321** [comment]
0.11 implements a new search engine which should help with querying pages of items.
