### ISSUE TITLE
[RFC] Bulk & metadata import

### ISSUE THREAD

**Issue by boi123212321** [boi123212321/porn-manager#208]
Metadata import would require some kind of explanation of how the data is organized, or require one specific format that JSON/YAML files would need to follow.
The first approach would end up in a more dynamic system, but it's harder to maintain and will probably have some edge cases.
Basic example json
``` json
[
   {
      "name":"Test",
      "birth_date":"1995-05-05",
      "tags":[
         "a",
         "b",
         "c"
      ],
      "hair_color":"Brown"
   },
   {
      "name":"Test2",
      "birth_date":"1994-04-04",
      "tags":[
         "d",
         "e"
      ],
      "hair_color":"Blonde"
   }
]
```
To create actors from such a file, the program would need some explanation of what is stored where, something like:
``` json
{
   "type":"actor",
   "fields": {
      "name":"name",
      "bornOn":{
         "path":"birth_date",
         "type":"date",
         "dateFormat":"YYYY-MM-DD"
      },
      "labels":"tags",
      "custom":{
         "hairColor":{
            "path":"hair_color",
            "type":"MULTI_SELECT"
         }
      }
   }
}
```
whereby custom: { ... } are the custom data fields that will be introduced in 0.10.0. Every custom data field needs a name and a type, so in this case we want hair_color from the JSON to be stored in hairColor, which has a type of "MULTI_SELECT", which will render as a multiple-choice dropdown box in the UI. If the custom field is already defined, it will use that instead of creating a new one. Same for labels.
This would be able to essentially import any kind of JSON/YAML to mass import scenes/actors/movies/images (images would strictly require a file path).

Alternatively, a fixed format could be used, so no parsing has to be done (quicker to develop, easier to maintain), however, this would require users to transform files that don't fit the format **before** importing:
So the imported JSON would have to look like this instead:
``` json
[
   {
      "name":"Test",
      "bornOn":15125125125125,
      "labels":[
         "a",
         "b",
         "c"
      ],
      "custom":{
         "hairColor":{
            "type":"MULTI_SELECT",
            "value":"Brown"
         }
      }
   },
   {
      "name":"Test2",
      "bornOn":12512512512512,
      "labels":[
         "d",
         "e"
      ],
      "custom":{
         "hairColor":{
            "type":"MULTI_SELECT",
            "value":"Blonde"
         }
      }
   }
]
```
(Birth dates would need to be JS Date compatible values (https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date).

**Comment by tritnaha** [comment]
"Plain" JSON seems like the most suitable option to me, but that's just based off how resources like metadataapi/json-porn/theporndb supply their data.

**Comment by GernBlanston12** [comment]
I take it you'd pair this up (the "import" tool) with a tool that scraped websites via actress name, set up to output a .json in this format, based on a list of names?  In my case, I have (via Pornganizer) a folder full of actress pics named as the actress is named, and I can access my tables in Pornganizer for metadata.  I can handle bulk edit of a file set up like this, to sub the file path for a profile pic, but I'd have to construct something more complex to output this based off the tables I have in PG and/or use a scraper based on a list of names of the profile images I have.

**Comment by boi123212321** [comment]
https://github.com/boi123212321/porn-manager/issues/269
