### ISSUE TITLE
[RFC] Scraping actor info

### ISSUE THREAD

**Issue by boi123212321** [boi123212321/porn-manager#209]
Related to https://github.com/boi123212321/porn-manager/issues/172

With custom data fields, users will be able to attach any kind of metadata to actors (and less importantly scenes etc).

When an actor is created, some info could be scraped from public databases (e.g. FreeOnes, Data18, IAFD). Alternatively there could be a manual action to run a scraper (maybe optionally in dry mode (not mutating the database)).

There are two ways to do this:
JS plugin functions vs. YAML/JSON scraper schemas.

JS plugins could be saved into a folder next to the program and then referenced in the config. That file would contain a function that defines how the scraping takes place.
``` javascript
async function (ctx) {
  // ctx would contain relevant info like
  // the actor name that is being searched,
  // and modules to fetch and parse HTML

  // TODO: Fetch a website
  // Scrape info

  // Return data to program
  return {
    labels: ["a", "b", "c"],
    custom: {
      hairColor: "red"
    }
  }
}
```
Note that JS functions can be parsed and allocated during runtime, so no recompiling required, when adding/changing scraper functions.
Scrapers could be installed in the config like:
``` json
{
  "SCRAPERS": [
    {
      "name": "FreeOnes Scraper",
      "path": "./scrapers/freeones.js",
      "active": false,
      "type": "actor"
    }
  ]
}
```
active = true would run the scraper when an actor is added for example.

I think this is a much more powerful solution than trying to build a custom scraper solution, as all features of Javascript can be leveraged and files are still exchangeable between users.

**Comment by tritnaha** [comment]
imho JS seems like the most sane option here.

**Comment by boi123212321** [comment]
https://github.com/boi123212321/porn-manager/wiki/Scrapers

**Comment by boi123212321** [comment]
https://github.com/boi123212321/porn-manager/wiki/Let's-write-an-actress-birth-date-scraper-(Plugin-example)
