### ISSUE TITLE
[Bug] The password is shown in plain sight in the url

### ISSUE THREAD

**Issue by tltgt** [boi123212321/porn-manager#212]
Please hide the password and not include it in the url.

**Comment by echo6ix** [comment]
> boiii1232112/15/2019
> yeah that don't take the password function too seriously lmao

> boiii1232112/15/2019
> i just implemented it so it's not streaming porn into my LAN

**Comment by boi123212321** [comment]
^ That too

 I will change it to a token based authentication at some point though
