### ISSUE TITLE
[Feature] Docker support

### ISSUE THREAD

**Issue by binarygeek119** [boi123212321/porn-manager#239]
i like to run this in unraid
right now i will run it as a vm
but would like if it could be moved over into a docker format

**Comment by boi123212321** [comment]
unfortunately i have 0% skill in Docker...
some Docker pro would have to do this for us

**Comment by Tweeticoats** [comment]
I've opened up pull #297 with a basic docker file and a wrapper script.
This uses a multi stage build to:
- Start with a node base image.
- Copy all source to the docker image, compile and build.
- Start with a basic debian:buster runtime image.
- copy the compiled files to the new image.
- install ffmpeg from debian
- copy example configuration files and wrapper script.

I needed a wrapper shell script and example configuration files as I want to store configuration files in /config/ as docker images are generally designed to be thrown out so you usually want to use a persistent volume to store configuration and databases.
Inside the container it will look for videos in /videos/ and /images/ for images so you generally want to bind mount the directory where the videos are stored into the container.

Building:
`docker build -t porn-manager .`

Running:
```
docker volume create porn-manager-config
docker run -it --name=porn-manager -p 3000:3000 --restart=always -v porn-manager-config:/config -v /path_to_video:/videos:ro -v /path_to_images:/images:ro porn-manager
```

**Comment by boi123212321** [comment]
6251bff505a4f83baa7d0f0d41b33cb934848c3c
