### ISSUE TITLE
[Feature] Additional users + user-management

### ISSUE THREAD

**Issue by tritnaha** [boi123212321/porn-manager#241]
**Is your feature request related to a problem? Please describe.**
It'd be great if we could have the ability to add additional users with their own unique login-details without having to do this by deploying a reverse-proxy. An additional feature that would complement this would be per-user permissions to scanned/monitored folders, assuming there are multiple folders to choose from (IE, similar to plex)

Perhaps even offer the ability to restrict what content users can see based on tags, where for example a user can only see content tagged "gay" and have anything else excluded.

**Describe the solution you'd like**
The addition of a user-management tab in the UI to add/remove users and restrict access to content based on its tags.

**Comment by boi123212321** [comment]
I just don't see this happening in the foreseeable future
