### ISSUE TITLE
[Feature] UI: Ability to Adjust Actor/Scene/Studio/Etc Thumbnail Size

### ISSUE THREAD

**Issue by echo6ix** [boi123212321/porn-manager#327]
**Is your feature request related to a problem? Please describe.**
The size of thumbnails for actors, movies, scenes, images, and studios is currently fixed. It's not the most efficient use of screen real estate depending on the end-user's display viewport size.

**Describe the solution you'd like**
Let the end-user adjust the size of these thumbnails on-the-fly, by adding a thumbnail size option in the navigation drawer. Preferably an [icon button](https://fontawesome.com/icons/text-size?style=solid) that has a drop down [scale slider](https://uimovement.com/design/balloon-slider/) when clicked to adjust the thumbnail size. Let the app remember the size selected throughout sessions by writing to a cookie (or whatever method is preferable). 

**Additional context**
Each section -- actors, images, scenes, etc -- would remember it's own size preference. For instance, I like the default size of the scenes thumbnail, but I would want to set the size of the actor thumbnails smaller.

To reduce the amount of space used in the navigation drawer also consider the following:
- Show favorites only could be reduced to an [icon button](https://fontawesome.com/icons/heart?style=solid)
- Show bookmarks only could be reduced to an [icon button](https://fontawesome.com/icons/bookmark)
- Star rating filter could be reduced to an [icon button](https://fontawesome.com/icons/star?style=solid)
- There would need to a visual indicator on the icon button to demonstrate it's actively filter results.

**Comment by boi123212321** [comment]
thumbnails are based on the aspect ratio, it's not fixed.

**Comment by boi123212321** [comment]
for the 2nd half of your issue
see https://github.com/boi123212321/porn-manager/issues/472
