### ISSUE TITLE
[Feature] UI: Change Layout/Behaviour of Labels in Navigation Drawer

### ISSUE THREAD

**Issue by echo6ix** [boi123212321/porn-manager#328]
**Is your feature request related to a problem? Please describe.**
Currently the navigation drawer contains all the labels in a scroll-able div container.  When the end-user has a lot of labels it becomes tedious to scroll through the list to find the desired label.

**Describe the solution you'd like**

##### Do not display all the labels by default
Remove the list of labels entirely. Instead have a label query form. When the form becomes activated show a drop down list of all the labels that is filtered as the user types.

##### Display labels the user has entered
The list of desired label(s) the user has selected should be displayed under the label query form. Retain the current behavior where clicking one of these labels is essentially deleting it from the filter.

##### Add a simple method to clear all user-entered labels
On the far right of the label query form add an icon button that clears all the activated labels from the filter.

##### Add a simple method to clear individual user-entered labels
Perhaps add the ability to click a label to deactivate it, removing it from the list of entered labels

**Comment by boi123212321** [comment]
this doesn't take into account that labels have 3 states: deselected, allow (items are required to have that label) and disallow (items are not allowed to have that tag).
Right now this is only implemented for scenes, but will be an option for all listings.

**Comment by echo6ix** [comment]
@boi123212321 Thanks for the reply. I see that behaviour now. I wasn't aware all the states did any of that. I think I can work that behaviour into my proposal and in a way that might be more intuitive for users.

Starting from the premise that there is no list of labels, only a query form.
- The user begins typing in the label form
- A drop down list appears with all labels, and as the user types the list is progressively filtered. [Example](https://browsernative.com/wp-content/uploads/chrome-omnibox-search-suggestions-1.png).
- When the user finds the label they want they either click the label name or enter a carriage return and the label is selected
- The selected label is added below the query form.
  - The presentation of the label is in the form of a button with a drop down caret like [this](https://i.imgur.com/2F072VN.png)
  - The drop down caret is a visual indicator that lets the user know there are more options available (because I had no idea about the different states of labels without any visual indicator)
  - The drop down menu via the caret has the options for the three states: `allow`, `disallow`, `remove`.
  - The color of the button can change based on the state, eg `allow` would be red or something like that.
  - In mobile mode clicking a small caret might not be feasible, so just the entire button needs to be clicked to see the drop down menu of the three states

Thoughts?
