### ISSUE TITLE
[Feature] Studio page redesign

### ISSUE THREAD

**Issue by boi123212321** [boi123212321/porn-manager#373]

**Comment by echo6ix** [comment]
I've always thought xHamster's [channel page](https://xhamster.com/channels) [studios] is one of the best iterations of a studio page.

- It displays studios in a grid card format which this app already does
- It displays both the logo and hero image (which you've already incorporated for actors in v0.15) in the card, for a beautiful presentation
- The textual studio name is presented in the card for clarity
- Number of videos is displayed to gauge collection size
- The subscribe button would be useless here, but I suppose that's where a favorite or bookmark button could go?
- The page scales nicely on different view-ports, as well as the mobile version, which removes the hero image and resizes the cards smaller -- both iterations are good.

Everything about that page is amazing. It's a good blend of form and function imo. My idea is don't recreate the wheel, use theirs 👍 

As an aside I also like the idea that they have the option to display all the studios in a grid format by textual studio name only [scroll all the way to the bottom on their channel page to see it], and the included alphabet strip to navigate sections.

**Comment by echo6ix** [comment]
> boiii12321Today at 9:27 PM
> i should clarify, i'm talking about the studio details

TBH, the structure of the current page is pretty good. I would leave it the way it is for the most part except for some tweaks and polishing.

For the tweaks I'd take inspiration from Pornhub's [studio-specific landing page.](https://www.pornhub.com/channels/tushy) except ignore the wrapper on the left which has a lot of wasted space imo. 

- Again, the hero image with the logo is a nice touch.
- Below the hero image container I'd have a div that displays all the tags associated with the studio like xHamster does [here on their page](https://xhamster.com/channels/private-society/newest). I've never been a fan of the "Label" heading and glyph personally. I think it's visually self-explanatory that they're tags/labels based on how they appear with the rounded border and all.
- Juxtaposed to the labels, and using the same visual format as the labels, but in a different color I'd put the amount of videos (with a movie real icon), and the amount of actors (with an avatar icon) associated with the studio. 
- I also like how that xHamster page has tabs that lets you sort the scenes by newest or oldest.
- For primary studio pages, I'd display the subsidiary studios basically as you have them now, but as cards like I described them in the post above -- with the logo overlayed on a hero image in a card.
  - When the view port turns into a mobile mode, just remove the hero image from the card and display the logo
- I would add an opaque background and border around the headings that read "featuring" and " "scenes" as PornHub does. And I'd make the font the same size as the actor names and scene titles.
- If a studio description exists I'd personally display on the right side of my proposed hero image, in a white font on a semi-opaque black div.
- The only unique idea I have is: After the "featuring" and "scene" blocks, make a "related labels" block, which contains a list all the labels tagged from all scenes associated with the studio in a grid format.

These might be a lot more specific suggestions than you're going for. If so my apologies.
