### ISSUE TITLE
[Feature] Expanded Actor Details Page

### ISSUE THREAD

**Issue by Herpes2000** [boi123212321/porn-manager#375]
It would be nice to view the following information on an actors profile page (preferably all of this content on one screen with options to minimize or maximize certain sections)

scenes 
movies (displaying the dvd covers of movies the star appears in)
actors that appear with this actor in scenes (this emulates the 'scene pairings' that you can access on IAFD)

**Comment by boi123212321** [comment]
https://github.com/boi123212321/porn-manager/commit/5cc1cc58bcfebdbc3c470fe05116c041e7c92c14
