### ISSUE TITLE
[Feature] Multiple Tags on Marker

### ISSUE THREAD

**Issue by yoshnopa** [boi123212321/porn-manager#376]
When marking a spot, it is possible to associate it with a label already. This is a good step, but sometimes, multiple labels are appropriate for the same marker. 

For example, a blowjob marker could be added deep throat, a sex position can be anal additionally and so on.

Also, it could be of interest to make the labels of the markers part of the overall scene (as a scene with a cowgirl marker should turn up when i search for the label cowgirl) or at least make this an option the same way the actors labels are added to scenes. Another alternative would be to make markers its own tab like studios, actors etc.

I would be willing to contribute to that with a little guidance through the code base.

**Comment by boi123212321** [comment]
This was already planned, and will come in the next next major update.
However right now, markers are not associated with a label, it's just a recommendation when you choose its name.
See: https://github.com/boi123212321/porn-manager/issues/273

**Comment by boi123212321** [comment]
Ability to search/filter for markers will be added in 0.16

**Comment by boi123212321** [comment]
https://github.com/boi123212321/porn-manager/issues/387
