### ISSUE TITLE
[Feature] Category specific labels

### ISSUE THREAD

**Issue by yoshnopa** [boi123212321/porn-manager#377]
Depending on how labels are given, they may only apply for a certain type of element. If that is the case, those labels will clutter up the system on the other pages.

In practice, lets say I want to make a label for hair color, like blonde, brunette etc.
Those are not necessarily of interest for me when searching for videos, but when I am searching actors, they should appear. Movies may have labels about their story arc which may not be applicable to singular scenes. And lastly, images may be described with properties describing the pose, which do not apply to any other field. 

Combining all of this and more would make the label search really messy, the simplest solution would be to simply add some checkboxes for the areas the labels are applied for. 

Again I can help with that.

More sophisticated, for no user interaction would be needed, would be to only show labels that apply to at least one element in the chosen area (scenes/movies/actors/images). This would be the smartest, but from looking at the current structure, this is not easily done here. I may be wrong of course and this may change in the future.

**Comment by boi123212321** [comment]
I have this implemented for custom data fields, so it shouldn't be too hard to copy the logic over I think.
