### ISSUE TITLE
[Bug] Firefox video preview clogs network

### ISSUE THREAD

**Issue by yoshnopa** [boi123212321/porn-manager#388]
**Describe the bug**
When hovering over a scene, a short preview is played. When this happens, the loading does not stop even when removing the mouse on firefox, meaning high bandwith usage continuing, which also prevents other images or videos from loading as it waits for the video to load. The video however is the original file, meaning it normally takes gigabytes, so this doesn't stop, resulting in freezes, timeouts, not loaded images and in general a clogged network. 
Stops only via F5/Ctrl+R.
It doesn't occur on chrome.

**To Reproduce**
1. Open porn-manager in firefox 73.0.1 (64 Bit, Linux Ubuntu)
2. Go to scenes
3. Hover over a scenes thumbnail for a second until the video starts to play
4. Leave the area, the video stops playing

**Expected behavior**
Network usage should go down, when loading further info it should go faster and images should be lazy-loaded on them. 

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04 LTS
 - Browser: Firefox
 - Version: 73.0.1

**Comment by boi123212321** [comment]
Not entirely sure, but 3aea0d7fb0d0d673c563c759d09429660a3457c1 may fix it.
Anyhow, it's iffy behavior by Firefox - I always noticed Firefox getting slower, this might be at least one cause for it.

**Comment by yoshnopa** [comment]
This is fixed, makes a huge difference in speed, thanks!
