### ISSUE TITLE
[Bug] PornDB-Scraper stop working with rc6

### ISSUE THREAD

**Issue by ferengi82** [boi123212321/porn-manager#428]
**Describe the bug**
geting errors when running the scene / actor plugin (https://github.com/ThePornDB/porn-manage-scene-scraper) in 1.4. they work fine.

**To Reproduce**
1. clean install
2. add porndb scrapers
3. add one video-folder and disable most things in config for testing

[config.json.txt](https://github.com/boi123212321/porn-manager/files/4396709/config.json.txt)

4. start porn-manager

**Expected behavior**
should add scenes with data from porn-db

**Screenshots**
when its scraping the scenes i got this error
<img width="1086" alt="error1" src="https://user-images.githubusercontent.com/5311407/77816539-ad7ff800-70c3-11ea-8742-ff3aafcf94e9.PNG">

The scenes where added to the Home-Screen:
<img width="300" alt="scenes1" src="https://user-images.githubusercontent.com/5311407/77816556-d6a08880-70c3-11ea-9af2-5c3c04de89b3.PNG">

But not to the scenes tab, when i click on "scenses" it got this error:
<img width="1096" alt="error2" src="https://user-images.githubusercontent.com/5311407/77816544-b96bba00-70c3-11ea-86a7-d704a41b8462.PNG">

after every restart i geht this:
<img width="1087" alt="restart" src="https://user-images.githubusercontent.com/5311407/77816602-20896e80-70c4-11ea-81c8-02c4f6824bbd.PNG">

**Comment by ferengi82** [comment]
some more testing, same error without plugins activated

<img width="780" alt="error3" src="https://user-images.githubusercontent.com/5311407/77817006-e0c48600-70c7-11ea-89bf-96628b424abb.PNG">

**Comment by boi123212321** [comment]
I think this is due to a rogue twigs process (the search engine) running on your system or something. It's definitely not related to the plugin or plugins in general, as I couldn't reproduce this on a RC6 clean install. Make sure no twigs process is running.

**Comment by ferengi82** [comment]
your right, a few twigs processes where running in the background, thanks!
