### ISSUE TITLE
[Feature] Autotagger to ignore symbols and spaces

### ISSUE THREAD

**Issue by lameeagl** [boi123212321/porn-manager#441]
**Is your feature request related to a problem? Please describe.**
A video with for example "mylifeinmiami" in the title will no be matched properly with the studio "My Life In Miami" unless the alias "mylifeinmiami" is added

**Describe the solution you'd like**
I would like for the autotagger to ignore upper/lower case letters, symbols and spaces. So i do not have to add aliases to studioes in this degree. If a studio has multiple words. It should match with those words seperate as well as with them having .com behind. 
So instead of the studio "My Life In Miami" only matches with videos that have that in the title. It should match with "*My*Life*In*Miami*"

**Comment by boi123212321** [comment]
> I would like for the autotagger to ignore upper/lower case letters, symbols and spaces

It does that already, as seen here:
```typescript
export function stripStr(str: string) {
  return str.toLowerCase().replace(/[^a-zA-Z0-9'/\\,()[\]{}]/g, "");
}

// Returns IDs of extracted studios
export async function extractStudios(str: string): Promise<string[]> {
  const allStudios = await Studio.getAll();
  return allStudios
    .filter(
      studio =>
        stripStr(str).includes(stripStr(studio.name)) ||
        (studio.aliases || []).some(alias =>
          stripStr(str).includes(stripStr(alias))
        )
    )
    .sort((a, b) => b.name.length - a.name.length)
    .map(s => s._id);
}
```
Evil Angel matches EvilAngel for example.

**Comment by boi123212321** [comment]
Pretty sure this is still working, until proven otherwise
