### ISSUE TITLE
[Feature] Search resolution

### ISSUE THREAD

**Issue by lameeagl** [boi123212321/porn-manager#442]
**Describe the solution you'd like**
It would be nice if automatic labels could be added based on resolution. So that videos with a resolution of 3840x2160 automatically would have the 4K label added. The videos with a resolution of 1920x1080 would have the HD tag added and so on. Or at least sorting by resolution would be nice

**Comment by boi123212321** [comment]
You can sort by resolution.

Also, the full object is provided for plugins (as ctx.scene), so this could be done with a plugin.
