### ISSUE TITLE
[Bug] <Error when entering scane>

### ISSUE THREAD

**Issue by bubooe** [boi123212321/porn-manager#455]
(node:11896) UnhandledPromiseRejectionWarning: TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (C:\snapshot\pornmanager\node_modules\express\lib\response.js:425:11)
    at C:\snapshot\porn-manager\build\server.js:134:17
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\porn-manager\build\server.js:5:58)
    at <anonymous>
(node:11896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by boi123212321** [comment]
i think this is fixed as of https://github.com/boi123212321/porn-manager/commit/95fbfc1d83148a1b6b86999f21471846bc2aa27d
