### ISSUE TITLE
[Feature] Bulk add Label

### ISSUE THREAD

**Issue by ARandomCat** [boi123212321/porn-manager#466]
**Is your feature request related to a problem? Please describe.**
A way to bulk-add a label to the current selection of images / videos would be useful 

**Describe the solution you'd like**
If you select images/videos you can already delete them. Adding an "Add Label" button which opens a popup in which you can select the label to add to the menu would be useful.

**Comment by boi123212321** [comment]
see https://github.com/boi123212321/porn-manager/issues/205
