### ISSUE TITLE
Plugins fail

### ISSUE THREAD

**Issue by kcossel** [boi123212321/porn-manager#504]
**Issue**:  When creating actor plugin attempts to run, but fails claiming not a valid plugin.
![image](https://user-images.githubusercontent.com/36736594/80493942-af8bdf80-892b-11ea-9a1c-bf061db3abff.png)

**Steps**:  Fresh install of 0.20.0-rc.4 to test plugin.  Copied freeones_age.js from wiki page. Add new actor then plugin fails.
![image](https://user-images.githubusercontent.com/36736594/80494220-0a253b80-892c-11ea-9824-20ce5dc58c81.png)

I have tried with other plugins from https://github.com/ThePornDB/porn-manage-scene-scraper and get the same error message.

**Comment by boi123212321** [comment]
0.20 has changed the way plugins need to be written. If the plugin definition doesn't start with module.exports =, it's an outdated plugin.
I added 0.20 version to my plugin repo.

**Comment by kcossel** [comment]
That fixed my problem.  Thank you.
